### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull request bumps the version so we can build a fresh AMI.

## 💭 Motivation and context ##

The previous AMI is getting long in the tooth, so we are overdue for a rebuild.

## 🧪 Testing ##

All `pre-commit` hooks pass.  I also built a staging AMI and deployed it to our staging COOL environment and verified that it functions as expected.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - _eschew scope creep!_
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.
- [x] Create and test a staging AMI with these changes.

## ✅ Pre-merge checklist ##

- [x] Finalize version.

## ✅ Post-merge checklist ##

- [x] Create a production AMI with these changes.

### CODE REVIEW

**Review by dav3r — APPROVED** [review]

**Review by mcdonnnj — APPROVED** [review]
Should this be a minor version bump? This seems more like a patch/build bump, but I might be mistaken.

**Comment by jsf9k** [comment]
> Should this be a minor version bump? This seems more like a patch/build bump, but I might be mistaken.

This is the first build after the Lineage PR that changed the base AMI from Buster to Bullseye.  Since the bump didn't happen there, I'm making it happen here.

**Comment by mcdonnnj** [comment]
> > Should this be a minor version bump? This seems more like a patch/build bump, but I might be mistaken.
> 
> This is the first build after the Lineage PR that changed the base AMI from Buster to Bullseye. Since the bump didn't happen there, I'm making it happen here.

Not trying to derail things, but I see the Bullseye change as part of the `v1.0.1` tag+release. Am I missing something?

**Comment by jsf9k** [comment]
> > > Should this be a minor version bump? This seems more like a patch/build bump, but I might be mistaken.
> > 
> > 
> > This is the first build after the Lineage PR that changed the base AMI from Buster to Bullseye. Since the bump didn't happen there, I'm making it happen here.
> 
> Not trying to derail things, but I see the Bullseye change as part of the `v1.0.1` tag+release. Am I missing something?

Ugh.  You are correct.  I will fix.

**Review by dav3r — APPROVED** [review]
👍

**Review by mcdonnnj — APPROVED** [review]

**Pull request merged**
